# Generated by Django 3.0.7 on 2020-07-23 18:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Порода')),
                ('code', models.CharField(max_length=255, verbose_name='Код')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Кличка')),
                ('age', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(150)], verbose_name='Возраст')),
                ('description', models.TextField(verbose_name='Описание')),
                ('photo', models.ImageField(null=True, upload_to='photos', verbose_name='Фото')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.Breed', verbose_name='Порода')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.Type', verbose_name='Вид')),
            ],
        ),
        migrations.AddField(
            model_name='breed',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.Type', verbose_name='Вид'),
        ),
    ]
